title: "Emery Lab"
description: "Migration, ancestry, and health in the Nile Valley using isotopic and genomic approaches."
theme: minima

header_pages:
  - about.md
  - research.md
  - publications.md
  - join.md
