title: "Emery Lab"
description: "Migration, ancestry, and health in the Nile Valley using isotopic and genomic approaches."

remote_theme: "mmistakes/minimal-mistakes@4.24.0" # <--- pin a stable, Pages-compatible version!

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

header_pages:
  - about.md
  - research.md
  - publications.md
  - join.md
