title: "<img src='/assets/images/bad_lab.png' style='height:40px; vertical-align: middle;'> The BAD Lab"
description: "The Binghamton Ancient DNA Lab — Exploring the Past Through Genomics and Archaeology."
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-include-cache

minimal_mistakes_skin: "air"  # Light skin, white background, green accents we'll add!

header_pages:
  - about.md
  - research.md
  - publications.md
  - join.md

author:
  name: "BAD Lab"
  avatar: "/assets/images/badlab_logo.png"  # This adds it to the header!
  bio: "The Binghamton Ancient DNA Lab investigates human migrations, ancestry, and health using ancient genomics and isotopic science."

# Social media
social:
  links:
    - label: "ORCID"
      icon: "fas fa-id-badge"
      url: "https://orcid.org/your-orcid-id"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=your-profile-id"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:yourname@binghamton.edu"

# SEO
google_site_verification: ""
